version: '3.1'

services:
  web:
    restart: always
    image: go-mysql-crud
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8005:8005
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
      - "DB_NAME=go_mysql_crud"
      - "DB_PASS=really-bad-idea"
  
  mysql:
    image: mysql:5.7
    command: --init-file /data/app/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: 'really-bad-idea'
      MYSQL_ROOT_USER: root
    ports:
      - 3306:3306
    volumes:
      - /tmp/data:/var/lib/mysql
      - ./init.sql:/data/app/init.sql
    
