apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  labels:
    io.kompose.service: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      labels:
        io.kompose.service: mysql
    spec:
      containers:
        - args:
            - --init-file
            - /data/app/init.sql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: really-bad-idea
            - name: MYSQL_ROOT_USER
              value: root
          image: mysql:5.7
          name: mysql
          ports:
            - containerPort: 3306
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: mysql-claim0
            - mountPath: /data/app/init.sql
              name: mysql-claim1
      restartPolicy: Always
      volumes:
        - name: mysql-claim0
          persistentVolumeClaim:
            claimName: mysql-claim0
        - name: mysql-claim1
          persistentVolumeClaim:
            claimName: mysql-claim1
status: {}
