apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.23.0 (HEAD)
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.23.0 (HEAD)
      labels:
        io.kompose.service: web
    spec:
      containers:
        - env:
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: go_mysql_crud
            - name: DB_PASS
              value: really-bad-idea
            - name: DB_PORT
              value: "3306"
          image: tensuredemoapp.azurecr.io/web:latest
          name: web
          ports:
            - containerPort: 8005
          resources: {}
      restartPolicy: Always
status: {}
